### ISSUE TITLE
AntiCheat Not Working

### ISSUE THREAD

**Issue by Dctrrr** [Tecnio/AntiHaxerman#20]
I keep getting this error what do I do?

[11:37:03 ERROR]: Could not load 'plugins/AntiHaxerman-3.0.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: club/quar/plugin/QuarPlugin at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] Caused by: java.lang.NoClassDefFoundError: club/quar/plugin/QuarPlugin at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_292] at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_292] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_292] at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_292] at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_292] at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_292] at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_292] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_292] at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_292] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445] at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292] at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292] at java.lang.Class.forName0(Native Method) ~[?:1.8.0_292] at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_292] at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.8.8.jar:git-PaperSpigot-445] ... 6 more Caused by: java.lang.ClassNotFoundException: club.quar.plugin.QuarPlugin at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_292] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445] at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292] at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292] at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_292] at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_292] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_292] at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_292] at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_292] at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_292] at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_292] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_292] at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_292] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445] at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292] at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292] at java.lang.Class.forName0(Native Method) ~[?:1.8.0_292] at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_292] at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.8.8.jar:git-PaperSpigot-445] ... 6 more

**Comment by hinoobers** [comment]
Did you build it yourself

**Comment by Dctrrr** [comment]
yep

**Comment by hinoobers** [comment]
a shading issue probs then
