### ISSUE TITLE
 Cannot invoke "Object.getClass()" because "o" is null

### ISSUE THREAD

**Issue by ghost** [Tecnio/AntiHaxerman#34]
[10:22:42 ERROR]: Error occurred while enabling AntiHaxerman v4.0.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
at me.tecnio.ahm.libs.ghast.reflections.Reflection$1.get(Reflection.java:105) ~[?:?]
at me.tecnio.ahm.libs.ghast.reflections.ReflectUtil.getChannelFuture(ReflectUtil.java:52) ~[?:?]
at me.tecnio.ahm.libs.ghast.listener.injector.InjectorModern.<init>(InjectorModern.java:37) ~[?:?]
at me.tecnio.ahm.libs.ghast.listener.injector.InjectorFactory.buildInjector(InjectorFactory.java:22) ~[?:?]
at me.tecnio.ahm.libs.ghast.listener.ChannelListener.<init>(ChannelListener.java:32) ~[?:?]
at me.tecnio.ahm.libs.ghast.PacketManager.init(PacketManager.java:40) ~[?:?]
at me.tecnio.ahm.AHM.registerPacketAPI(AHM.java:94) ~[?:?]
at me.tecnio.ahm.AHM.start(AHM.java:62) ~[?:?]
at me.tecnio.ahm.AHMPlugin.onEnable(AHMPlugin.java:9) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PandaSpigot-119]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-PandaSpigot-119]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:454) ~[patched_1.8.8.jar:git-PandaSpigot-119]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:393) ~[patched_1.8.8.jar:git-PandaSpigot-119]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-119]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.8.8.jar:git-PandaSpigot-119]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603) ~[patched_1.8.8.jar:git-PandaSpigot-119]
at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-119]
at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by Tecnio** [comment]
Use the proper bug report template.

**Comment by F3F5** [comment]
add a proper bug report template
btw don't fix
